export declare const PROPERTY_LIST: string[];
export declare const PROPERTY_VARIANTS: {
    animation: string[];
    appearance: string[];
    "background-clip": string[];
    "backdrop-filter": string[];
    "column-gap": string[];
    "user-select": string[];
    "text-fill-color": string[];
};
export declare const STATE_LIST: string[];
export declare const MEDIA_LIST: string[];
export declare const ALIASES: {
    backdrop: string;
    bg: string;
    "bg-attachment": string;
    "bg-blend": string;
    "bg-clip": string;
    "bg-color": string;
    "bg-image": string;
    "bg-position": string;
    "bg-repeat": string;
    "bg-size": string;
    radius: string;
    "radius-top": string[];
    "radius-bottom": string[];
    "radius-left": string[];
    "radius-right": string[];
    "radius-bl": string;
    "radius-br": string;
    "radius-tl": string;
    "radius-tr": string;
    m: string;
    mt: string;
    mb: string;
    ml: string;
    mr: string;
    mx: string[];
    my: string[];
    p: string;
    pt: string;
    pb: string;
    pl: string;
    pr: string;
    px: string[];
    py: string[];
    "min-w": string;
    "max-w": string;
    "min-h": string;
    "max-h": string;
    w: string;
    h: string;
    gradient: string;
    "radial-gradient": string;
    "conic-gradient": string;
    "flex-dir": string;
    "grid-rows": string;
    "grid-flow": string;
    "row-start": string;
    "row-span": string;
    "grid-cols": string;
    "col-start": string;
    "col-span": string;
    "col-gap": string;
    "auto-cols": string;
    "auto-rows": string;
    e: string;
    overscroll: string;
    "overscroll-x": string;
    "overscroll-y": string;
    inset: string[];
    "inset-x": string[];
    "inset-y": string[];
    z: string;
    decoration: string;
    "v-align": string;
    ws: string;
    ring: string;
    leading: string;
    tracking: string;
    break: (v: any) => string[];
    truncate: string[];
    "text-clip": string[];
    grid: string;
    "space-x": string;
    "space-y": string;
    "space-x-rev": string;
    "space-y-rev": string;
    "space-x-alt": string;
    "space-y-alt": string;
    "sr-only": (v: any) => "-opis-sr-only" | "-opis-not-sr-only";
    stack: string;
};
export declare const DEFAULT_VALUES: {
    truncate: string[];
    "text-clip": string[];
};
export declare const VALUE_WRAPPER: {
    gradient: (value: any) => string;
    "radial-gradient": (value: any) => string;
    "conic-gradient": (value: any) => string;
    "grid-rows": (v: any) => string;
    "row-span": (v: any) => string;
    "grid-cols": (v: any) => string;
    "col-span": (v: any) => string;
    e: (v: any) => any;
    ring: (v: any) => string;
    "font-size": (v: any) => any;
    leading: (v: any) => any;
    tracking: (v: any) => any;
    radius: (v: any) => any;
    "radius-top": (v: any) => any;
    "radius-left": (v: any) => any;
    "radius-bottom": (v: any) => any;
    "radius-right": (v: any) => any;
    "radius-tl": (v: any) => any;
    "radius-bl": (v: any) => any;
    "radius-tr": (v: any) => any;
    "radius-br": (v: any) => any;
    break: (v: any) => string[] | "break-word" | "break-all";
    grid: (v: any) => string;
};
